image: ruby:2.5
 
docs:
  stage: build
  script: 
    - apt-get update -yqq && apt-get install -yqq ncftp
    - |
        echo "Merge marker sanity check"
        (grep -ri "<<<<<<" * --exclude=deploy.sh || grep -ri ">>>>>>" * --exclude=deploy.sh) && (echo "found some merge conflicts, will abort"; exit -1)

        bundle install
        bundle exec jekyll build --config _config.yml,_versions.yml

        if [[ $CI_COMMIT_REF_NAME =~ ^.*x-.*$ ]]; then

          echo "Upload for branch $CI_COMMIT_REF_NAME"
          ncftpput -R -v -u $ftp_username -p $ftp_password docs.search-guard.com  "/$CI_COMMIT_REF_NAME" ./_site/*
          echo "Last commit message: $CI_COMMIT_MESSAGE"
          if [[ $CI_COMMIT_MESSAGE == *"noindex"* ]]; then
            echo "Skipping Search Index"
          else
            echo "Rebuilding Search Index"
            jekyll algolia push --config _config.yml,_versions.yml              
          fi
        else 
          echo "No upload for branch $CI_COMMIT_REF_NAME
        fi