image: ruby:2.5
 
docs:
  stage: build
  script: 
    - cat /etc/debian_version || true 
    - uname -a
    - apt-get update -yqq && apt-get install -yqq ncftp wget
    - wget https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_amd64
    - chmod +x yq_linux_amd64
    - ./yq_linux_amd64 -V || true 
    - ./deploy.sh