markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: "1..2"
  parse_block_html: false
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-relative-links
  - algoliasearch-jekyll

elasticsearch:
  currentversion: 6.8.0
  previousversion: 6.7.2

searchguard:
  esmajorversion: 6
  majorversion: 6.x-20
  fullversion: 6.2.2-20.1
  nextminorversion: 6.2.2-20.2
  nextmajorversion: 6.2.2-21.0
  islatestversion: false
  allversions:
    - 7x-35
    - 6x-25
    - 6x-24
    - 6x-23
    - 6x-22
    - 6x-21
    - 6x-20
    - v5
    - v2

docroots: 
  7x-35: latest
  6x-25: 6.x-25
  6x-24: 6.x-24
  6x-23: 6.x-23
  6x-22: 6.x-22
  6x-21: 6.x-21
  6x-20: 6.x-20
  v5: v5
  v2: v2
    
index: false

labels:
  navigation:
    quickstart: Quickstart
    first_steps: First Steps
    installation: Installing Search Guard
    upgrading: Upgrading Search Guard
    tls: TLS Setup
    configuration: "Applying Configuration Changes"
    authauth: Authentication and Authorization
    rolespermissions: "Users, Roles and Permissions"
    eeadvanced: Advanced Security Features
    dlsfls: Document- and Field-Level Security
    kibana: Kibana
    auditlog: Audit Logging
    compliance: Compliance
    restapi: REST API
    esstack: Integrating with the Elastic stack
    esclients: Elasticsearch clients
    xpack: X-Pack Integration
    ccs: Cross Cluster Search and Tribe
    integration_other: Other Integrations
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    resources: Resources
    7x-35: Search Guard 7.x-35
    6x-25: Search Guard 6.x-25
    6x-24: Search Guard 6.x-24
    6x-23: Search Guard 6.x-23
    6x-22: Search Guard 6.x-22
    6x-21: Search Guard 6.x-21
    6x-20: Search Guard 6.x-20
    v5: Search Guard 5
    v2: Search Guard 2
  collections:
    docs: Documentation
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    resources: Resources


relative_links:
  enabled:     true
  collections: true

domain: https://docs.search-guard.com
baseurl: /6.x-20

collections:
  docs:
    output: true
    permalink: :title
  troubleshooting:
    output: true
    permalink: :title
  changelogs:
    output: true
    permalink: :title
  resources:
    output: true
    permalink: :title

algolia:
  application_id: '2ESDTH812Y'
  index_name:     '6x-20'
  record_css_selector: 'h1, h2, h3, h4, h5'
  allowed_extensions:
    - html
  settings:
    minWordSizefor1Typo: 4
    minWordSizefor2Typos: 8
    hitsPerPage: 20
    maxValuesPerFacet: 100
    version: 2
    attributesToIndex:
      - tags
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - text_all
    attributesToRetrieve: 
      - collection_name
      - text_all
      - unique_hierarchy
      - css_selector
      - url
      - tags
    ignorePlurals: true
    removeStopWords: true
    distinct: true
    attributesForFaceting:
      - category_name
      - h1
    attributesToSnippet: 
      - "text_all:150"
    attributesToHighlight:
      - text
      - text_all
    paginationLimitedTo: 1000
    attributeForDistinct: unique_hierarchy
    exactOnSingleWordQuery: attribute
    disableTypoToleranceOnAttributes:
      - h1
      - h2
      - h3
    ranking: 
      - typo
      - geo
      - words
      - filters
      - proximity
      - attribute
      - exact
      - custom
    customRanking:
      - desc(posted_at)
      - desc(weight.tag_name)
      - asc(weight.position)
    separatorsToIndex: "."
    removeWordsIfNoResults: lastWords
    queryType: prefixLast
    snippetEllipsisText: "..."
    alternativesAsExact: 
      - ignorePlurals
      - singleWordSynonym

eol:
  features:
    - 7.3.0
    - 7.2.1
  updates:
    - 6.8.2

sgversions:
  #esv |sgv |kbv |feat|upd|eol
  search-guard-6:
      #esv |sgv |kbv |feat|upd|eol|available
    - 6.8.3|25.5|18.5|yes|yes|no|yes
    - 6.8.2|25.5|18.5|yes|yes|no|yes
    - 6.8.1|25.5|18.5|yes|yes|no|yes
    - 6.8.0|25.5|18.5|yes|yes|yes|yes
    - 6.7.2|25.5|18.5|yes|yes|no|yes
    - 6.7.1|25.5|18.5|no|no|yes|yes
    - 6.7.0|25.5|18.5|no|no|yes|yes
    - 6.6.2|25.5|18.5|yes|yes|no|yes
    - 6.6.1|25.5|18.5|no|no|yes|yes
    - 6.6.0|25.5|18.5|no|no|yes|yes
    - 6.5.4|25.5|18.5|no|yes|no|yes
    - 6.5.3|25.5|18.5|no|no|yes|yes
    - 6.5.2|25.5|18.5|no|no|yes|yes
    - 6.5.1|25.5|18.5|no|no|yes|yes
    - 6.4.3|25.5|17|no|yes|no|yes
    - 6.4.2|25.5|17|no|no|yes|yes
    - 6.4.1|25.5|17|no|no|yes|yes
    - 6.4.0|25.5|17|no|no|yes|yes
    - 6.3.2|25.5|17|no|no|yes|yes
    - 6.3.1|25.5|17|no|no|yes|yes
    - 6.3.0|25.5|17|no|no|yes|yes
    - 6.2.4|23.0|14|no|no|yes|no
    - 6.2.3|23.0|14|no|no|yes|no
    - 6.2.2|23.0|14|no|no|yes|no
    - 6.2.1|23.0|14|no|no|yes|no
    - 6.1.4|22.3|12|no|no|yes|no
    - 6.1.3|22.3|12|no|no|yes|no
    - 6.1.2|22.3|12|no|no|yes|no
    - 6.1.1|22.3|12|no|no|yes|no
    - 6.1.0|22.3|12|no|no|yes|no
